version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: "http://proxy.iutbourg.univ-lyon1.fr:3128"
        HTTPS_PROXY: "http://proxy.iutbourg.univ-lyon1.fr:3128"
    container_name: symfony_apache
    volumes:
      - ./public:/var/www/html/public
      - ./var:/var/www/html/var
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
